name = "Caterpilar"
width = 1280
height = 600

#[camera]
#	position = { x = 0, y = 0, z = 50 }
#	rotation = { x = 0, y = 0, z = 0 }

[camera]
	position = { x = 0, y = 0, z = 10 }
	rotation = { x = 0, y = 0, z = 0 }

#branches
[[objects]]
	type = "CYLINDER"
	light = "DIFFUSE"
	radius = 3
	color = { r = 136, g = 66, b = 29 }
	position = { x = 0, y = 0, z = 0 }
	rotation = { x = 0, y = 0, z = 80 }

[[objects]]
	type = "CYLINDER"
	light = "DIFFUSE"
	radius = 1
	color = { r = 136, g = 66, b = 29 }
	position = { x = 40, y = 0, z = 0 }
	rotation = { x = 0, y = 0, z = 100 }

#chenille
[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.6
	color = { r = 58, g = 137, b = 35}
	position = { x = 0, y = 0, z = 3 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.6
	color = { r = 58, g = 137, b = 35}
	position = { x = 0.6, y = -0.2, z = 3 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.6
	color = { r = 58, g = 137, b = 35}
	position = { x = 1.2, y = -0.4, z = 3 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.6
	color = { r = 58, g = 137, b = 35}
	position = { x = 1.8, y = -0.7, z = 3 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.6
	color = { r = 58, g = 137, b = 35}
	position = { x = 2.4, y = -1, z = 3 }

#yeux 
[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.15
	color = { r = 180, g = 180, b = 180}
	position = { x = -0.19, y = 0.4, z = 3.4 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.15
	color = { r = 180, g = 180, b = 180}
	position = { x = -0.4, y = 0, z = 3.4 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.1
	color = { r = 0, g = 0, b = 0}
	position = { x = -0.20, y = 0.4, z = 3.46 }


[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 0.1
	color = { r = 0, g = 0, b = 0}
	position = { x = -0.41, y = 0, z = 3.46 }

#picots
[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 0, y = 0.2, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = -0.1, y = -0.2, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 0.5, y = 0, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x =0.4, y = -0.4, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 1, y = -0.2, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x =0.9, y = -0.6, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 1.5, y = -0.4, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x =1.4, y = -0.8, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 2, y = -0.6, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x =1.9, y = -1, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x = 2.5, y = -0.8, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[objects]]
	type = "CONE"
	light = "PHONG"
	angle = 2
	revolution = false
	color = { r = 253, g = 63, b = 146 }
	position = { x =2.4, y = -1.2, z = 5 }
	rotation = { x = 92.1, y = 0, z = 0.3 }

[[lights]]
	position = {x = 0, y = 0, z = 60 }
	color = { r = 255, g = 255, b = 255 }
	intensity = 0.1
	expose = 50