
name = "Disco Room"
width = 1280
height = 800

# [[filters]]
# 	type = "NEGATIVE"

[camera]
    type = "PERSPECTIVE"
    position = { x = 0, y = 0, z = 1.0 }
    rotation = { x = 0, y = 0, z = 0 }

# MUR DROITE
[[objects]]
    type = "PLANE"
	position = { x = 1.5, y = 0, z = 0 }
    rotation.z = 90
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.8
		[objects.material.material]
			type = "ZOOM_UV"
			zoom = 1.1
			[objects.material.material.material]
				type = "TEXTURE"
				texture = "./scenes/img/70_wallpaper.png"

# MUR GAUCHE
[[objects]]
    type = "PLANE"
	position = { x = -1.5, y = 0, z = 0 }
    rotation.z = -90
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.8
		[objects.material.material]
			type = "ZOOM_UV"
			zoom = 1.1
			[objects.material.material.material]
				type = "TEXTURE"
				texture = "./scenes/img/70_wallpaper.png"

# BACKGROUND

[[objects]]
	type = "PLANE"
	position = { x = 0, y = 0, z = -5 }
	rotation.x = 90
	[objects.material]
		type = "MOVE_UV"
		v = 0.4
		[objects.material.material]
		type = "TEXTURE"
		texture = "./scenes/img/snow_background.jpg"

# VERRE FENETRE
[[objects]]
	type = "DIFFERENCE"
	position = { x = -0.75, y = 0, z = -4.25 }
    rotation = { x = 90, y = 0, z = 0 }
	[objects.material]
		type = "REFLECTION"
		transparency = 40
		reflection = 40
		[objects.material.color]
			type = "COLOR"
			color = { r = 200, g = 200, b = 255 }
	[objects.first]
		type = "BOX"
		position.y = 0.1
		min = { x = -0.25, y = -0.25, z = -0.25 }
		max = { x = 0.25, y = 0.25, z = 0.5 }
	[objects.second]
		type = "BOX"
		min = { x = -0.25, y = -0.25, z = -0.25 }
		max = { x = 0.25, y = 0.25, z = 0.5 }

# CONTOUR FENETRE
[[objects]]
	type = "DIFFERENCE"
	position = { x = -0.755, y = -0.25, z = -4 }
	[objects.material]
		type = "MARBLE"
		size = 2
		[objects.material.material]
			type = "COLOR"
			color = { r = 255, g = 255, b = 255 }
	[objects.first]
		type = "BOX"
		min = { x = -0.29, y = -0.29, z = -0.00001 }
		max = { x = 0.29, y = 0.54, z = 0.00001 }
	[objects.second]
		type = "BOX"
		min = { x = -0.25, y = -0.25, z = -0.25 }
		max = { x = 0.25, y = 0.5, z = 0.25 }

# MUR FOND / FENETRE
[[objects]]
    type = "DIFFERENCE"
	material.type = "DIFFUSE"
	material.albedo = 0.8
	material.material.type = "TEXTURE"
	material.material.texture = "./scenes/img/70_wallpaper.png"
	position = { x = 0, y = 0, z = -4 }
    rotation = { x = 90, y = 0, z = 0 }
	[objects.first]
		type = "PLANE"
	[objects.second]
		type = "BOX"
		position.x = -0.75
		min = { x = -0.25, y = -0.25, z = -0.25 }
		max = { x = 0.25, y = 0.25, z = 0.5 }

# PLAFOND
[[objects]]
    type = "PLANE"
	position = { x = 0, y = 1, z = 0 }
	rotation.x = 180
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.8
		[objects.material.material]
			type = "TEXTURE"
			texture = "./scenes/img/purple.jpg"
		# color = { r = 255, g = 218, b = 51 }

# SOL
[[objects]]
    type = "PLANE"
	position = { x = 0, y = -1, z = 0 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.8
		[objects.material.material]
			type = "CHECKERBOARD"
			size = 6
			[objects.material.material.white]
				type = "COLOR"
				color = { r = 102, g = 40, b = 146 }
			[objects.material.material.black]
				type = "COLOR"
				color = { r = 253, g = 177, b = 40 }

# tableau mimi mathy
[[objects]]
    type = "BOX"
    radius = 0.5
    position = { x = 1.78, y = 0, z = -3 }
    rotation = { x = 0, y = -90, z = 0}
    min = { x = -0.3, y = -0.3, z = -0.3 }
    max = { x = 0.3, y = 0.3, z = 0.3 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.8
		[objects.material.material]
			type = "TEXTURE"
			texture = "./scenes/img/mimie-mathy.png"

# disco ball
[[objects]]
    type = "SPHERE"
    radius = 0.2
    position = { x = 0, y = 0.8, z = -4 }
    [objects.material]
		type = "REFLECTION"
		reflection = 80
		[objects.material.color]
			type = "TEXTURE"
			texture = "./scenes/img/disco_ball.jpg"

# lights sol
[[lights]]
    type = "SPOT"
    position = { x = 0, y = 0.9, z = -1.2 }
	direction = { x = 0, y = -1, z = -1 }
	angle = 15
    intensity = 3

# light coin droit
[[lights]]
    type = "SPOT"
    position = { x = 0, y = 0, z = -2.5 }
	direction = { x = 1.0, y = 1, z = -2 }
	angle = 16
    intensity = 3

# light coin gauche
[[lights]]
    type = "SPOT"
    position = { x = 0, y = 0, z = -2.5 }
	direction = { x = -1.0, y = 1, z = -2 }
	angle = 14
    intensity = 3

# light disco ball

[[lights]]
    type = "SPOT"
    position = { x = 0.5, y = 0, z = -4 }
	direction = { x = -1.0, y = 2, z = 0 }
	angle = 15
    intensity = 3

[[lights]]
    type = "SPOT"
    position = { x = -0.5, y = 0, z = -4 }
	direction = { x = 1.0, y = 2, z = 0 }
	angle = 15
    intensity = 3

# light tableau
[[lights]]
    type = "SPOT"
    position = { x = 0.8, y = 0.9, z = -3 }
	direction = { x = 1.9, y = -2, z = 0 }
	angle = 23
    intensity = 3

[[lights]]
	type = "DIRECTIONAL"
	position.z = -4.5
	direction.z = -1.0
	intensity = 1.5

[[lights]]
    type = "AMBIENT"
    intensity = 0.2
