name = "Flower"
width = 1200
height = 1000

[camera]
	position = { x = 0, y = 0, z = 40}
	rotation = { x = 0, y = 0, z = 0 }

# [camera]
# 	position = { x = 0, y = 40, z = 0}
# 	rotation = { x = -90, y = 0, z = 0 }


[[objects]]
	type = "SPHERE"
	light = "DIFFUSE"
	radius = 5
	color = { r = 128, g = 128, b = 129}
	position = { x = 0, y = 0, z = 0 }

[[objects]]
	type = "PLANE"
	light = "DIFFUSE"
	color = { r = 128, g = 128, b = 128 }
	position = { x = 0, y = 0, z = -4 }
	rotation = { x = 90, y = 0, z = 0 }

[[lights]]
	position = {x = -15, y = -10, z = 10 }
	color = { r = 255, g = 165, b = 0}
	intensity = 0.5
	expose = 50

[[lights]]
	position = {x = -15, y = 10, z = 10 }
	color = { r = 255, g = 0, b = 147}
	intensity = 0.5
	expose = 50


[[lights]]
	position = {x = 0, y = 10, z = 10 }
	color = { r = 255, g = 165, b = 0}
	intensity = 0.5
	expose = 50

[[lights]]
	position = {x = 15, y = 10, z = 10 }
	color = { r = 255, g = 0, b = 147}
	intensity = 0.5
	expose = 50

[[lights]]
	position = {x = 15, y = -10, z = 10 }
	color = { r = 255, g = 165, b = 0}
	intensity = 0.5
	expose = 50

[[lights]]
	position = {x = 0, y = -10, z = 10 }
	color = { r = 255, g = 0, b = 147}
	intensity = 0.5
	expose = 50