name = "Rebound Spheres"
width = 1280
height = 800

[camera]
	type = "PERSPECTIVE"
	position = { x = 0, y = 0.5, z = 1.0 }
	rotation = { x = 0, y = 0, z = 0 }

[video]
	frame_sec = 10
	secondes = 1.5
	# type = "VIDEO"

# [[filters]]
# 	type = "ANTI_ALIASING"
# 	size = 10

# BIG SPHERES
[[objects]]
	type = "SPHERE"
	radius = 1.0
	position = { x = 1.0, y = 0.9, z = -4 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "REFLECTION"
			reflection = 90
			[objects.material.material.color]
				type = "COLOR"
				color = { r = 120, g = 240, b = 240 }

[[objects]]
	type = "SPHERE"
	radius = 1.0
	position = { x = -0.2, y = 0.9, z = -7 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "REFLECTION"
			reflection = 90
			[objects.material.material.color]
				type = "COLOR"
				color = { r = 220, g = 230, b = 105 }

[[objects]]
	type = "SPHERE"
	radius = 1.0
	position = { x = -1.8, y = 0.9, z = -10 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "REFLECTION"
			reflection = 90
			[objects.material.material.color]
				type = "COLOR"
				color = { r = 210, g = 130, b = 80 }

# SOL
[[objects]]
	type = "PLANE"
	position = { x = 0, y = -0.1, z = 0 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 100, g = 180, b = 255 }

# PETITES SPHERES
[[objects]]
	type = "SPHERE"
	position = { x = -0.5, y = 0.03, z = -1 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 200, g = 255, b = 12 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.1, y = 0.03, z = -2.1 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 36, g = 21, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -1, y = 0.03, z = -1.3 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 140, g = 49, b = 247 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 0.1, y = 0.03, z = -2 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 65, g = 149, b = 244 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 0.33, y = 0.03, z = -1.8 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 186, g = 170, b = 12 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 0.3, y = 0.03, z = -2.4 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 84, g = 121, b = 223 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 1.5, y = 0.03, z = -3 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 147, g = 38, b = 54 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -1.1, y = 0.03, z = -2.2 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 36, g = 221, b = 24 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = -0.33, y = 0.03, z = -1.7 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 236, g = 142, b = 0 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = -0.73, y = 0.03, z = -1.2 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 142, g = 236, b = 0 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 0.3, y = 0.03, z = -0.8 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 236, g = 0, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = 0.7, y = 0.03, z = -1 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 236, g = 142, b = 0 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = 0.63, y = 0.03, z = -1.5 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 0, g = 142, b = 236 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = 1.0, y = 0.03, z = -2.0 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 163, g = 118, b = 42 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -1.7, y = 0.03, z = -5.1 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 94, g = 203, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.7, y = 0.03, z = -2.3 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 98, g = 136, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.45, y = 0.03, z = -2.9 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 21, g = 168, b = 239 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.98, y = 0.03, z = -2.47 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 147, g = 57, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.89, y = 0.03, z = -3.5 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 76, g = 194, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = 0, y = 0.03, z = -3.2 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 39, g = 246, b = 114 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.23, y = 0.03, z = -3.4 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 246, g = 21, b = 142 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -1.84, y = 0.03, z = -4.54 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 44, g = 146, b = 170 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02
[[objects]]
	type = "SPHERE"
	position = { x = -0.12, y = 0.03, z = -1.1 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 21, g = 142, b = 36 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[objects]]
	type = "SPHERE"
	position = { x = -0.67, y = 0.04, z = -3.24 }
	radius = 0.05
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "COLOR"
			color = { r = 142, g = 36, b = 21 }
			[[objects.video]]
				seconde = { from = 0, to = 0.6 }
				position.y = -0.07
			[[objects.video]]
				seconde = { from = 0.6, to = 0.72 }
				position.y = -0.02
			[[objects.video]]
				seconde = { from = 0.78, to = 1.3 }
				position.y = +0.07
			[[objects.video]]
				seconde = { from = 1.3, to = 1.5 }
				position.y = +0.02

[[lights]]
	type = "POINT"
	position = { x = 1.5, y = 1.0, z = 0 }
	intensity = 3

[[lights]]
	type = "AMBIENT"
	intensity = 0.6
