name = "Snowman"
width = 1280
height = 800

#[camera]
#	position = { x = 2, y = 0, z = -3 }
#	rotation = { x = 0, y = 90, z = 0 }

[camera]
	type = "PERSPECTIVE"
	position = { x = 0, y = 0, z = 1 }
	rotation = { x = 0, y = 0, z = 0 }


#corps
[[objects]]
	type = "SPHERE"
	radius = 0.4
	position = { x = 0, y = -0.5, z = -3 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 169, g = 169, b = 169 }

[[objects]]
	type = "SPHERE"
	radius = 0.3
	position = { x = 0, y = 0.1, z = -3 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 169, g = 169, b = 169 }

#chapeau
[[objects]]
	type = "CONE"
	angle = 13
	revolution = false
	position = { x = 0.1, y = 0.6, z = -3}
	rotation = { x = 0,y = 0, z = -7 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.5
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.02
	position = { x = 0.1, y = 0.6, z = -3}
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 255, g = 255, b = 255 }

#yeux
[[objects]]
	type = "SPHERE"
	radius = 0.02
	position = { x = 0.1, y = 0.1, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.02
	position = { x = -0.1, y = 0.1, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

#nez
[[objects]]
	type = "CONE"
	angle = 5
	revolution = false
	position = { x = 0, y = 0.05, z = -2.5}
	rotation = { x = 92.1,y = 0, z = 0 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.7
		material.type = "COLOR"
		material.color = { r = 255, g = 165, b = 0 }

#bouche
[[objects]]
	type = "SPHERE"
	radius = 0.01
	position = { x = 0, y = -0.01, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.01
	position = { x = 0.025, y = -0.008, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.01
	position = { x = -0.025, y = -0.008, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.01
	position = { x = 0.05, y = -0.006, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.01
	position = { x = -0.05, y = -0.006, z = -2.72 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 0, g = 0, b = 0 }


#bouton
[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.6, z = -2.62 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.55, z = -2.61 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.5, z = -2.605 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.45, z = -2.61 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.4, z = -2.615 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.35, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.015
	position = { x = 0, y = -0.3, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 178, g = 0, b = 0 }

#nuage 1
[[objects]]
	type = "SPHERE"
	radius = 0.09
	position = { x = 1, y = 0.65, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 1.08, y = 0.6, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 1.08, y = 0.605, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 1, y = 0.605, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 1, y = 0.605, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 0.93, y = 0.605, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

#nuage 2
[[objects]]
	type = "SPHERE"
	radius = 0.09
	position = { x = -1, y = 0.6, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -1.08, y = 0.55, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -1.08, y = 0.555, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -1, y = 0.555, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -1, y = 0.555, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -0.93, y = 0.555, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

#nuage 3
[[objects]]
	type = "SPHERE"
	radius = 0.09
	position = { x = 0, y = 0.75, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -0.08, y = 0.7, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = -0.08, y = 0.705, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 0, y = 0.705, z = -2.69 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 0, y = 0.705, z = -2.63 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

[[objects]]
	type = "SPHERE"
	radius = 0.08
	position = { x = 0.07, y = 0.705, z = -2.66 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "CLOUD"
			size = [2.0, 8.0, 32.0, 64.0, 128.0, 256.0, 512.0, 1024.0]
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

#sol
[[objects]]
	type = "PLANE"
	position = { x = 0, y = -0.65, z = 0 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "MARBLE"
			size = 2
			material.type = "COLOR"
			material.color = { r = 255, g = 255, b = 255 }

#fond
[[objects]]
	type = "PLANE"
	position = { x = 0, y = 0, z = -4 }
	rotation = { x = 90, y = 0, z = 0 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		material.type = "COLOR"
		material.color = { r = 135, g = 206, b = 235 }

[[lights]]
	type = "POINT"
	position = { x = -5, y = 1, z = 1 }
	intensity = 1

[[lights]]
	type = "POINT"
	position = { x = 0, y = 0, z = 0 }
	intensity = 1

[[lights]]
	type = "DIRECTIONAL"
	position.y = 100
	direction.y = -1
	intensity = 1.5

[[lights]]
	type = "AMBIENT"
	intensity = 0.2
