name = "Sphere"
width = 800
height = 800

#[camera]
#	position = { x = 0, y = 15, z = 40 }
#	rotation = { x = -30, y = 0, z = 0 }

[camera]
	position = { x = 15, y = 0, z = 40 }
	rotation = { x = 0, y = 30, z = 0 }

#[camera]
#	position = { x = 0, y = -19, z = 0 }
#	rotation = { x = 90, y = 0, z = 0 }

[[objects]]
	type = "SPHERE"
	light = "PHONG"
	radius = 5
	color = { r = 240, g = 230, b = 140}
	position = { x = 0, y = 0, z = 0 }

[[objects]]
	type = "PLANE"
	light = "DIFFUSE"
	color = { r = 135, g = 206, b = 235 }
	position = { x = 0, y = -20, z = 0 }

[[objects]]
	type = "PLANE"
	light = "DIFFUSE"
	color = { r = 135, g = 206, b = 235 }
	position = { x = 0, y = 0, z = -20}
	rotation = { x = 90, y = 0, z = 0 }

[[objects]]
	type = "PLANE"
	light = "DIFFUSE"
	color = { r = 135, g = 206, b = 235 }
	position = { x = -20, y = 0, z = -20}
	rotation = { x = 90, y = 90, z = 0 }

[[objects]]
	type = "PLANE"
	light = "DIFFUSE"
	color = { r = 135, g = 206, b = 235 }
	position = { x = 20, y = 0, z = -20}
	rotation = { x = 90, y = 90, z = 0 }

[[lights]]
	position = {x = 0, y = 20, z = 30 }
	color = { r = 255, g = 255, b = 255 }
	intensity = 0.1
	expose = 6

[[lights]]
	position = {x = 0, y = 0, z = 15 }
	color = { r = 255, g = 255, b = 255 }
	intensity = 0.5
	expose = 6