name = "Checkerboard"
width = 1280
height = 800

[camera]
    type = "PERSPECTIVE"
    position = { x = 0, y = 0, z = 0 }
    rotation = { x = 0, y = 0, z = 0 }

[[objects]]
    type = "BOX"
    position = { x = -0.75, y = 0.5, z = -3 }
	rotation = { x = 45, y = 45, z = 0}
	min = { x = -0.25, y = -0.25, z = -0.25 }
	max = { x = 0.25, y = 0.25, z = 0.25 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "REFLECTION"
			transparency = 40
			[objects.material.material.color]
				type = "CHECKERBOARD"
				size = 10
				[objects.material.material.color.white]
					type = "COLOR"
					color = { r = 150, g = 0, b = 255 }
				[objects.material.material.color.black]
					type = "COLOR"
					color = { r = 255, g = 0, b = 150 }

[[objects]]
    type = "PLANE"
    position = { x = 0, y = -1.0, z = -3 }
	rotation.x = 60
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
		type = "COLOR"
		color = { r = 255, g = 255, b = 255 }

[[objects]]
    type = "CONE"
    radius = 0.8
    position = { x = -0.1, y = 0.2, z = -3 }
    rotation = { x = 0, y = 0, z = 10 }
	angle = 20
	revolution = false
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "REFLECTION"
        transparency = 50
        [objects.material.material.color]
            type = "TEXTURE"
            texture = "./scenes/img/brick.png"

[[objects]]
    type = "CYLINDER"
    radius = 0.3
    position = { x = 0.5, y = 0.5, z = -3 }
	rotation = { x = 0, y = 0, z = 45 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
			type = "REFLECTION"
			transparency = 80
			[objects.material.material.color]
				type = "VORONOI"
				size = 30
				u = 0
				v = 0
				[objects.material.material.color.material]
					type = "COLOR"
					color = { r = 0, g = 255, b = 150 }

[[objects]]
    type = "SPHERE"
    radius = 0.3
    position = { x = -0.75, y = -0.5, z = -3 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "REFLECTION"
        transparency = 20
        [objects.material.material.color]
            type = "COLOR"
            color = { r = 150, g = 255, b = 0 }

[[lights]]
	type = "AMBIENT"
	intensity = 0.5

[[lights]]
	type = "POINT"
	position = { x = 0.65, y = 0, z = -1 }
	intensity = 3.0
