name = "Snowman"
width = 1280
height = 800

#[camera]
#	position = { x = 2, y = 0, z = -3 }
#	rotation = { x = 0, y = 90, z = 0 }

[camera]
	position = { x = 0, y = 0, z = 1 }
	rotation = { x = 0, y = 0, z = 0 }


#corps
[[objects]]
	type = "BOX"
	material = "NORMAL"
	radius = 0.4
	min = { x = -0.25, y = -0.25, z = -0.25 }
	max = { x = 0.25, y = 0.25, z = 0.25 }
	position = { x = 0, y = -0.5, z = -3 }
	rotation = { x = 0, y = 45, z = 0 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.3
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0, y = 0.1, z = -3 }


[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.02
	color = { r = 255, g = 255, b = 255 }
	position = { x = 0.1, y = 0.6, z = -3}

#yeux
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.02
	color = { r = 0, g = 0, b = 0 }
	position = { x = 0.1, y = 0.1, z = -2.72 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.02
	color = { r = 0, g = 0, b = 0 }
	position = { x = -0.1, y = 0.1, z = -2.72 }

#bouche
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.01
	color = { r = 0, g = 0, b = 0 }
	position = { x = 0, y = -0.01, z = -2.72 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.01
	color = { r = 0, g = 0, b = 0 }
	position = { x = 0.025, y = -0.008, z = -2.72 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	material = "NORMAL"
	radius = 0.01
	color = { r = 0, g = 0, b = 0 }
	position = { x = -0.025, y = -0.008, z = -2.72 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.01
	color = { r = 0, g = 0, b = 0 }
	position = { x = 0.05, y = -0.006, z = -2.72 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.01
	color = { r = 0, g = 0, b = 0 }
	position = { x = -0.05, y = -0.006, z = -2.72 }


#bouton
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.6, z = -2.62 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.55, z = -2.61 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.5, z = -2.605 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.45, z = -2.61 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.4, z = -2.615 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.35, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.015
	color = { r = 178, g = 0, b = 0 }
	position = { x = 0, y = -0.3, z = -2.66 }

#nuage 1
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.09
	color = { r = 169, g = 169, b = 169 }
	position = { x = 1, y = 0.65, z = -2.66 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 1.08, y = 0.6, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 1.08, y = 0.605, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 1, y = 0.605, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 1, y = 0.605, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0.93, y = 0.605, z = -2.66 }

#nuage 2
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.09
	color = { r = 169, g = 169, b = 169 }
	position = { x = -1, y = 0.6, z = -2.66 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -1.08, y = 0.55, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -1.08, y = 0.555, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -1, y = 0.555, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -1, y = 0.555, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -0.93, y = 0.555, z = -2.66 }

#nuage 3
[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.09
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0, y = 0.75, z = -2.66 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -0.08, y = 0.7, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = -0.08, y = 0.705, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0, y = 0.705, z = -2.69 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0, y = 0.705, z = -2.63 }

[[objects]]
	type = "SPHERE"
	material = "NORMAL"
	radius = 0.08
	color = { r = 169, g = 169, b = 169 }
	position = { x = 0.07, y = 0.705, z = -2.66 }

[[lights]]
	position = {x = -5, y = 1, z = 1 }
	color = { r = 255, g = 255, b = 255 }
	intensity = 0.2
	expose = 21

[[lights]]
	position = {x = 0, y = 0, z = 0 }
	color = { r = 255, g = 255, b = 255 }
	intensity = 0.2
	expose = 21
