name = "Figure 2"
width = 600
height = 450


[camera]
	type = "PERSPECTIVE"
	position = { x = 0, y = 0.75, z = -0.75 }
	rotation = { x = -5, y = 0, z = 0 }

#sol
[[objects]]
	type = "PLANE"
	position = { x = 0, y = 0, z = -4 }
	[objects.material]
		type = "DIFFUSE"
		albedo = 1.0
		[objects.material.material]
			type = "COLOR"
			color = { r = 150, g = 150, b = 150 }

[[objects]]
	type = "SPHERE"
	position = { x = 0.5, y = 0.5, z = -3 }
	radius = 0.3
	[objects.material]
		type = "DIFFUSE"
		albedo = 0.9
		[objects.material.material]
				# type = "SPECULAR"
				# n = 100
				# 	[objects.material.material.material]
						type = "COLOR"
						color = { r = 232, g = 129, b = 249 }

[[lights]]
	type = "AMBIENT"
	intensity = 0.3

[[lights]]
	type = "POINT"
	position = { x = 1.0, y = 1.5, z = -2 }
	intensity = 1

[[lights]]
	type = "POINT"
	position = { x = 0.5, y = 1.5, z = -2 }
	intensity = 1

[[lights]]
	type = "POINT"
	position = { x = 1.5, y = 1.5, z = -2 }
	intensity = 1

