name = "Move Uv"
width = 1280
height = 800

[camera]
	type = "PERSPECTIVE"
	position = { x = 0, y = 0, z = 0 }
	rotation = { x = 0, y = 0, z = 0 }

[[objects]]
	type = "SPHERE"
	radius = 0.4
	position = { x = -0.9, y = 0, z = -3 }
	[objects.material]
			type = "TEXTURE"
			texture = "./scenes/img/mimie-mathy.png"

[[objects]]
	type = "SPHERE"
	radius = 0.4
	position = { x = 0, y = 0, z = -3 }
	[objects.material]
		type = "MOVE_UV"
		u = 0.1
		v = 0.1
		[objects.material.material]
			type = "TEXTURE"
			texture = "./scenes/img/mimie-mathy.png"

[[objects]]
	type = "SPHERE"
	radius = 0.4
	position = { x = 0.9, y = 0, z = -3 }
	[objects.material]
		type = "MOVE_UV"
		u = 0.2
		v = 0.2
		[objects.material.material]
		type = "TEXTURE"
		texture = "./scenes/img/mimie-mathy.png"

[[lights]]
	type = "AMBIENT"
	intensity = 0.2

[[lights]]
	type = "POINT"
	position = { x = -1, y = 0, z = 0}
	intensity = 1.5
