name = "random"
width = 1280
height = 800

[camera]
    type = "PERSPECTIVE"
    position = { x = 0, y = 0, z = 0 }
    rotation = { x = 0, y = 0, z = 0 }

[[objects]]
    type = "BOX"
    position = { x = -0.75, y = 0.5, z = -3 }
	rotation = { x = 45, y = 45, z = 0}
	min = { x = -0.25, y = -0.25, z = -0.25 }
	max = { x = 0.25, y = 0.25, z = 0.25 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "RANDOM"

[[objects]]
    type = "PLANE"
    position = { x = 0, y = -1.0, z = -3 }
	rotation.x = 60
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "COLOR"
		color = {r = 200, g = 200, b = 200}

[[objects]]
    type = "CONE"
    radius = 0.8
    position = { x = -0.1, y = 0.2, z = -3 }
    rotation = { x = 0, y = 0, z = 10 }
	angle = 20
	revolution = false
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "RANDOM"

[[objects]]
    type = "CYLINDER"
    radius = 0.3
    position = { x = 0.5, y = 0.5, z = -3 }
	rotation = { x = 0, y = 0, z = 45 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "RANDOM"

[[objects]]
    type = "SPHERE"
    radius = 0.3
    position = { x = -0.75, y = -0.5, z = -3 }
    [objects.material]
        type = "DIFFUSE"
		albedo = 0.9
    [objects.material.material]
        type = "RANDOM"

[[lights]]
	type = "AMBIENT"
	intensity = 0.5

[[lights]]
	type = "POINT"
	position = { x = 0.65, y = 0, z = -1 }
	intensity = 3.0

