#ifndef FILTER_TYPES_H
# define FILTER_TYPES_H

enum e_filters_type {
	FILTER_BLACK_AND_WHITE,
	FILTER_SEPIA,
	FILTER_NEGATIVE,
	FILTER_ANTI_ALIASING,
	FILTER_CARTOON,
	FILTER_BLUR,
	FILTER_DEPTH_CONTRAST,
	FILTER_MOTION_BLUR
};

#endif
